services:
  honeybot:
    image: miacx/honeybot:latest
    container_name: honeybot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - honeybot-data:/app/data

volumes:
  honeybot-data:
