{{- if and .Values.secret.create (not .Values.secret.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "honeybot.secretName" . }}
  labels:
    {{- include "honeybot.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.keys.discordToken }}: {{ .Values.secrets.discordToken | quote }}
  {{ .Values.secret.keys.openrouterApiKey }}: {{ .Values.secrets.openrouterApiKey | quote }}
  {{ .Values.secret.keys.apiKeyEncryptionKey }}: {{ .Values.secrets.apiKeyEncryptionKey | quote }}
{{- end }}
